// Note: This file was generated by an agent using the Playwright CLI.
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

const { login } = require('./login');
const { buildMockEvents } = require('./buildMockEvents');
const { installMockEventRoutes } = require('./installMockEventRoutes');
const { findEventCardByTitle } = require('./findEventCardByTitle');
const { parseCurrency } = require('./parseCurrency');

const email = 'sankarkuppusamykenjin@gmail.com';
const password = 'KLSP@family01';

// Venue is a constant supplied by the mock routes (installMockEventRoutes)
const MOCK_VENUE = 'Mock Venue';

// Custom controlled mock dataset (exactly 4 records)
const mockEvents = [
  { id: 'evt-hyd-conf', title: 'Hyderabad Tech Conference', category: 'conference', city: 'Hyderabad', price: 150, availableSeats: 50 },
  { id: 'evt-del-fest', title: 'Delhi Cultural Festival', category: 'festival', city: 'Delhi', price: 80, availableSeats: 200 },
  { id: 'evt-mum-concert', title: 'Mumbai Live Concert', category: 'concert', city: 'Mumbai', price: 120, availableSeats: 150 },
  { id: 'evt-blr-workshop', title: 'Bangalore Coding Workshop', category: 'workshop', city: 'Bangalore', price: 60, availableSeats: 75 }
];

// Tests run serially and share one page/session so Test 002 continues from
// the state Test 001 leaves behind (mocked + logged in + filtered catalog).
test.describe.serial('Assignment 5: Mocked EventHub flow', () => {
  let page;
  // Shared between tests: the mock event that Test 001 filters down to.
  let storedTarget;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();

    const harPath = path.join(__dirname, 'eventhub.har');
    if (fs.existsSync(harPath)) {
      await page.routeFromHAR(harPath, { notFound: 'fallback' });
    }

    // Install mocks BEFORE any navigation/login to avoid missing early requests
    await installMockEventRoutes(page, mockEvents);

    // Log any page errors for debugging
    page.on('pageerror', e => console.log('PAGE ERROR:', e.message));

    await login(page, email, password);
    await expect(page.locator('nav')).toBeVisible();
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('Test 001: Mocked events catalog displays controlled data', async () => {
    // Navigate via UI to ensure SPA routing works
    await page.getByTestId('nav-events').click();

    // Verify exactly 4 cards
    // Use stable card container instead of fragile parent traversal
    const cards = page.locator('article');
    await expect(cards).toHaveCount(4);

    // Verify titles + absence of live data
    for (const event of mockEvents) {
      await expect(page.locator(`text=${event.title}`)).toBeVisible();
    }
    await expect(page.locator('text=World Tech Summit')).toHaveCount(0);

    // Verify each card details
    for (const event of mockEvents) {
      const card = page.locator('article').filter({ has: page.locator(`a[href="/events/${event.id}"]`) });
      await expect(card).toBeVisible();

      const priceText = await card.getByText('$', { exact: false }).first().innerText();
      expect(parseCurrency(priceText)).toBe(event.price);

      await expect(card.getByText(`${event.availableSeats} seats available`)).toBeVisible();

      const link = await page.locator(`a[href="/events/${event.id}"]`).first().getAttribute('href');
      expect(link).toContain(`/events/${event.id}`);
    }

    // Filtering
    const target = mockEvents[0]; // Hyderabad conference

    await page.locator('input[placeholder*="Search"]').fill('Hyderabad');
    await page.locator('select').first().selectOption('Conference');
    await page.locator('select').nth(1).selectOption('Hyderabad');

    const filteredCards = page.locator('article');
    await expect(filteredCards).toHaveCount(1);

    const filteredCard = page.locator('article').filter({ has: page.locator(`a[href="/events/${target.id}"]`) });
    await expect(filteredCard).toBeVisible();

    const filteredPrice = parseCurrency(await filteredCard.getByText('$', { exact: false }).first().innerText());
    expect(filteredPrice).toBe(target.price);

    await expect(filteredCard.getByText(`${target.availableSeats} seats available`)).toBeVisible();

    // Store for next test (also annotate for reporting)
    storedTarget = target;
    test.info().annotations.push({ type: 'mockEvent', description: JSON.stringify(target) });
  });

  test('Test 002: Filtered mock event detail page matches catalog data', async () => {
    // Connected to Test 001: reuse the event it filtered down to.
    expect(storedTarget, 'Test 001 must run first and store a target event').toBeTruthy();
    const target = storedTarget;

    // From the filtered event card, click "Book Now" and navigate to the detail page.
    const filteredCard = page.locator('article').filter({ has: page.locator(`a[href="/events/${target.id}"]`) });
    await expect(filteredCard).toBeVisible();
    await filteredCard.locator('#book-now-btn').click();

    await page.waitForURL(`**/events/${target.id}`);
    expect(page.url()).toContain(`/events/${target.id}`);

    // Event title (h1) matches the stored mock title.
    await expect(page.locator('main h1')).toHaveText(target.title);

    // Price per ticket, venue, city and available seats match the stored mock details.
    const pricePerTicket = page.locator('//p[text()="Price per ticket"]/following-sibling::p');
    await expect(pricePerTicket).toBeVisible();
    expect(parseCurrency(await pricePerTicket.textContent())).toBe(target.price);

    await expect(page.locator('//p[text()="Venue"]/following-sibling::p')).toHaveText(MOCK_VENUE);
    await expect(page.locator('//p[text()="City"]/following-sibling::p')).toHaveText(target.city);
    await expect(page.locator('//p[text()="Available"]/following-sibling::p'))
      .toContainText(`${target.availableSeats} /`);

    // Ticket quantity starts at 1.
    const ticketCount = page.locator('#ticket-count');
    await expect(ticketCount).toHaveText('1');

    // Total amount equals the mock ticket price for quantity 1.
    const totalValue = page.locator('//span[text()="Total"]/following-sibling::span');
    await expect(totalValue).toHaveText(`$${target.price}`);
    expect(parseCurrency(await totalValue.textContent())).toBe(target.price);

    // Increase the ticket count to 2 using "+".
    await page.getByRole('button', { name: '+' }).click();

    // Assert quantity displays 2 (Playwright auto-waits for the UI update).
    await expect(ticketCount).toHaveText('2');

    // Assert the total value for quantity 2.
    await expect(totalValue).toHaveText(`$${target.price * 2}`);
    expect(parseCurrency(await totalValue.textContent())).toBe(target.price * 2);
  });
});
